---
name: 'Update plugins to force cache invalidation'
on: # yamllint disable-line
  schedule:
    - cron: '0 5 * * 4'
  workflow_dispatch:

jobs:
  update_plugins:
    name: Update date on plugins.txt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create a new branch
        run: git checkout -b "update_plugins"
      - name: append text to the end of file
        run: echo '# remove' >> setup.py
      - name: Add and Commit
        run: git add setup.py && git commit -m "testing" && git push origin update_plugins
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          base: main
          branch: update_plugins


